#!/usr/bin/env python
import sys
import matplotlib.pyplot as plt
import numpy as np
import elements, tso_reader

if len(sys.argv) != 2:
    sys.stderr.write("Usage: {0} TSO_FILE\n".format(sys.argv[0]))
    sys.exit(1)

data = tso_reader.read_tso(sys.argv[1])
log_scale = True

# display data
for i in range(data["ny"]):
    plt.plot(
        data["t"],
        data["y"][i],
        label=elements.symbols[data["zz"][i]]
    )
box = plt.axes().get_position()
plt.axes().set_position([box.x0, box.y0, box.width * 0.8, box.height])
plt.legend(loc="center left", bbox_to_anchor=(1, 0.5))
if log_scale:
    plt.axes().set_xscale("log")
    plt.axes().set_yscale("log")
plt.show()
