#!/usr/bin/env python
import sys
import matplotlib.pyplot as plt
import numpy as np
import tso_reader

if len(sys.argv) != 2:
    sys.stderr.write("Usage: {0} TSO_FILE\n".format(sys.argv[0]))
    sys.exit(1)

data = tso_reader.read_tso(sys.argv[1])

# display data
for i in range(data["ny"]):
    plt.plot(data["t"], data["y"][i])
plt.axes().set_xscale("log")
plt.axes().set_yscale("log")
plt.show()
